id: I7DDA1D4E
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:57:50.734535
last_modified: 2023-02-09 14:57:50.734655
source_metadata:
  title: 'RK: Kāśyapaparivarta'
  language: bo
bases:
  A4C4:
    base_file: A4C4.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
